[build-system]
requires = []
build-backend = "flit_core.buildapi"

[project]
name = "SITRI pdk documentation"
authors = [{ name = "kevinchen", email = "kevin_chen@latitudeda.com" }]
dynamic = ["version", "description"]
